#!/usr/bin/env python3
"""Phase 24E-B: deterministic generation + drift check for the runtime catalog.

The Phase 24D/24E-A builder (scripts/build_pack_catalog.py) can only describe
packs it generated itself: it composes runtime paths from a hardcoded template
(`packs/<id>/<id>-cards.js`) and requires a registry-handoff.json listing those
exact basenames. HSK predates that pipeline -- its cards payload is the
hand-installed `data.js` and its adapter is `packs/hsk/hsk-content-pack.js`,
and no handoff exists. So HSK is a LEGACY-INSTALLED pack and needs a descriptor
built from the runtime files that are actually on disk.

This module is that generator. It is deliberately GENERIC: nothing here branches
on the string "hsk". A pack is legacy-installed when its descriptor supplies
explicit `cardsPath`/`manifestPath` instead of inheriting the generated
template, and the same validation runs either way.

Checksum honesty (Phase 24E-B constraint):
  - contentChecksum is the sha256 of the runtime cards payload actually served.
    That is the byte-level integrity anchor for what the browser executes.
  - sourceChecksum is REQUIRED by pack-registry.js. Legacy HSK has no canonical
    source image (CSI), so we use the sha256 of the raw workbook bytes and say
    so explicitly in `install.sourceChecksumBasis`. We do NOT claim these are
    CSI bytes, and we invent no publisher, license, URL or legal status.

Run standalone to regenerate:  python tests/data/test_pack_catalog_legacy.py --emit
Run as a suite (drift check):  python tests/data/test_pack_catalog_legacy.py
"""

import hashlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
APP_ROOT = os.path.join(ROOT, "hsk_flashcard_app")
CATALOG_PATH = os.path.join(APP_ROOT, "packs", "catalog.js")

CATALOG_SCHEMA_VERSION = 1
GLOBAL_NAME = "window.FLASHEDU_CATALOG"
HEADER = (
    "// Generated by tests/data/test_pack_catalog_legacy.py --emit"
    " -- DO NOT EDIT MANUALLY.\n"
    "// schemaVersion: %d  packs: %d\n"
)

fails = []


def check(name, cond):
    if not cond:
        fails.append(name)


# --------------------------------------------------------------- primitives

def canonical_bytes(abs_path, binary=False):
    """Bytes as the repository canonically stores them (LF), not as checked out.

    core.autocrlf can hand us a CRLF working copy of a text file whose committed
    blob is LF (.gitattributes now pins eol=lf, but an already-checked-out tree
    keeps its CRLF until it is rewritten). Hashing the raw working copy would
    therefore embed a PLATFORM-DEPENDENT checksum in the catalog: generated on
    Windows it recorded hsk-content-pack.js as 5486 bytes, but a fresh clone
    serves the same file as 5386 bytes. The catalog would then disagree with the
    bytes actually deployed.

    Normalizing CRLF -> LF for text assets makes generation reproducible on any
    platform and matches what git stores and what a clone/deploy serves.
    Binary assets (the workbook) are hashed verbatim -- normalizing them would
    corrupt the hash.
    """
    with open(abs_path, "rb") as fh:
        data = fh.read()
    return data if binary else data.replace(b"\r\n", b"\n")


def sha256_file(abs_path, binary=False):
    return hashlib.sha256(canonical_bytes(abs_path, binary)).hexdigest()


def file_bytes(abs_path, binary=False):
    return len(canonical_bytes(abs_path, binary))


def js_json(obj):
    """Byte-identical to scripts/contentpack/emit.py::js_json."""
    text = json.dumps(obj, ensure_ascii=False, sort_keys=True,
                      separators=(",", ":"))
    text = text.replace("</", "<\\/")
    text = text.replace(" ", "\\u2028").replace(" ", "\\u2029")
    return text


def check_rel_path(value, field):
    """Mirror of pack-registry.js::checkRelPath. Raises ValueError."""
    if not isinstance(value, str) or not value:
        raise ValueError("%s must be a non-empty relative path" % field)
    if "://" in value:
        raise ValueError("%s must not be a URL" % field)
    if value.startswith("/") or value.startswith("//"):
        raise ValueError("%s must not be absolute or protocol-relative" % field)
    if value.startswith("\\") or "\\" in value:
        raise ValueError("%s must use forward slashes only" % field)
    if len(value) > 1 and value[1] == ":":
        raise ValueError("%s must not be drive-absolute" % field)
    for seg in value.split("/"):
        if seg == "..":
            raise ValueError("%s must not contain a '..' segment" % field)
        if seg == "":
            raise ValueError("%s must not contain an empty segment" % field)
    return value


def resolve_contained(rel_path, base_dir, field):
    """Resolve rel_path under base_dir and prove containment via realpath.

    Symlink-aware: a path that validates lexically but escapes the app root
    through a link is rejected here, before its bytes are ever hashed.
    """
    check_rel_path(rel_path, field)
    base_real = os.path.realpath(base_dir)
    target_real = os.path.realpath(os.path.join(base_dir, rel_path))
    if not (target_real == base_real or
            target_real.startswith(base_real + os.sep)):
        raise ValueError("%s escapes the app root: %s" % (field, rel_path))
    if not os.path.isfile(target_real):
        raise ValueError("%s does not exist: %s" % (field, rel_path))
    return target_real


# ------------------------------------------------------------- descriptors

# Facts transcribed from packs/hsk/hsk-content-pack.js (the live adapter).
# Nothing here is invented: every value is already present in the manifest or
# derivable from the runtime files on disk.
LEGACY_SOURCES = [
    {
        "packId": "hsk",
        "version": "1.0.0",
        "title": "HSK Tiếng Trung",
        "courseId": "hsk",
        "courseType": "exam",
        "status": "launch",
        "languageProfile": {
            "target": "zh-CN", "translation": "vi", "instruction": "vi",
            "script": "Hans", "direction": "ltr",
        },
        "audio": {
            "locale": "zh-CN",
            "fallbackLocales": ["zh"],
            "readFields": ["primaryPrompt", "exampleText"],
        },
        "search": {"fields": ["primaryPrompt", "pronunciation", "definition"]},
        "capabilities": [
            "study", "srs", "test", "audio", "frontReadingToggle", "examples",
            "translation", "bookmarks", "notes", "analytics",
        ],
        # Declared reserved block -- the OWNERSHIP scope for reset/analytics.
        # `allocated` below is only the currently observed occupancy.
        "idRange": {"min": 1, "max": 999999},
        "launch": {"visible": True, "readiness": "launch"},
        # Legacy-installed runtime assets: explicit paths, not the generated
        # `packs/<id>/<id>-*.js` template.
        "cardsPath": "data.js",
        "manifestPath": "packs/hsk/hsk-content-pack.js",
        "cardsGlobal": "HSK_CARDS",
        "sourcePath": "source_data/HSK1-HSK6.xlsx",
        "sourceChecksumBasis": "raw-workbook-bytes",
    },
]


def count_allocated(cards_abs, global_name):
    """Derive allocated {count,min,max} from the real cards payload.

    Parses the emitted JSON array rather than executing the script: the file is
    `window.<GLOBAL> = [ ... ];` and we slice between the first '[' and the
    final ']'. No JS is ever evaluated.
    """
    with open(cards_abs, "r", encoding="utf-8") as fh:
        text = fh.read()
    marker = "window." + global_name
    at = text.index(marker)
    start = text.index("[", at)
    end = text.rindex("]")
    rows = json.loads(text[start:end + 1])
    ids = [r["id"] for r in rows]
    return rows, {"count": len(ids), "min": min(ids), "max": max(ids)}


def build_entry(src, app_root):
    cards_abs = resolve_contained(src["cardsPath"], app_root,
                                  "%s.cardsPath" % src["packId"])
    manifest_abs = resolve_contained(src["manifestPath"], app_root,
                                     "%s.manifestPath" % src["packId"])
    if src["cardsPath"] == src["manifestPath"]:
        raise ValueError("cardsPath must differ from manifestPath")

    source_abs = os.path.join(ROOT, src["sourcePath"])
    if not os.path.isfile(source_abs):
        raise ValueError("source workbook missing: %s" % src["sourcePath"])

    rows, allocated = count_allocated(cards_abs, src["cardsGlobal"])
    ir = src["idRange"]
    if not (ir["min"] <= allocated["min"] and allocated["max"] <= ir["max"]):
        raise ValueError("allocated range falls outside the declared idRange")

    return rows, {
        "packId": src["packId"],
        "version": src["version"],
        "title": src["title"],
        "courseId": src["courseId"],
        "courseType": src["courseType"],
        "status": src["status"],
        "languageProfile": dict(src["languageProfile"]),
        "audio": dict(src["audio"]),
        "search": dict(src["search"]),
        "capabilities": list(src["capabilities"]),
        "idRange": dict(ir),
        "allocated": allocated,
        "launch": dict(src["launch"]),
        "manifestPath": src["manifestPath"],
        "cardsPath": src["cardsPath"],
        "cardsGlobal": src["cardsGlobal"],
        "contentChecksum": "sha256:" + sha256_file(cards_abs),
        # The workbook is binary: hashed verbatim, never newline-normalized.
        "sourceChecksum": "sha256:" + sha256_file(source_abs, binary=True),
        # Additive provenance honesty. pack-registry.js ignores unknown keys;
        # these exist so nobody later mistakes a workbook hash for a CSI hash.
        "install": {
            "kind": "legacy-installed",
            "contentChecksumBasis": "runtime-cards-payload-bytes",
            "contentChecksumPath": src["cardsPath"],
            "sourceChecksumBasis": src["sourceChecksumBasis"],
            "sourceChecksumPath": src["sourcePath"],
        },
        # Per-file runtime integrity for the two scripts the boot shim inserts.
        "runtimeAssets": {
            "cards": {
                "path": src["cardsPath"],
                "sha256": "sha256:" + sha256_file(cards_abs),
                "bytes": file_bytes(cards_abs),
            },
            "manifest": {
                "path": src["manifestPath"],
                "sha256": "sha256:" + sha256_file(manifest_abs),
                "bytes": file_bytes(manifest_abs),
            },
        },
    }


def assemble(entries, default_pack_id=None):
    packs = sorted(entries, key=lambda e: (e["idRange"]["min"], e["packId"]))
    catalog = {"schemaVersion": CATALOG_SCHEMA_VERSION, "packs": packs}
    if default_pack_id:
        catalog["defaultPackId"] = default_pack_id
    return catalog


def render_catalog_js(catalog):
    body = HEADER % (catalog["schemaVersion"], len(catalog["packs"]))
    body += "%s = %s;\n" % (GLOBAL_NAME, js_json(catalog))
    return body.encode("utf-8")


def generate():
    entries, all_rows = [], {}
    for src in LEGACY_SOURCES:
        rows, entry = build_entry(src, APP_ROOT)
        entries.append(entry)
        all_rows[src["packId"]] = rows
    catalog = assemble(entries, default_pack_id="hsk")
    return catalog, render_catalog_js(catalog), all_rows


# ------------------------------------------------------------------- tests

def main():
    if "--emit" in sys.argv:
        _, data, _ = generate()
        os.makedirs(os.path.dirname(CATALOG_PATH), exist_ok=True)
        with open(CATALOG_PATH, "wb") as fh:
            fh.write(data)
        sys.stdout.write("wrote %s (%d bytes)\n" % (CATALOG_PATH, len(data)))
        return 0

    catalog, data, all_rows = generate()

    # --- determinism: regeneration is byte-stable -------------------------
    _, data2, _ = generate()
    check("generation is byte-deterministic", data == data2)

    # --- drift: the committed catalog matches a fresh generation ----------
    check("catalog.js exists", os.path.isfile(CATALOG_PATH))
    if os.path.isfile(CATALOG_PATH):
        with open(CATALOG_PATH, "rb") as fh:
            committed = fh.read()
        check("committed catalog.js has no drift", committed == data)
        check("catalog.js is LF-only", b"\r\n" not in committed)
        check("catalog.js ends with a newline", committed.endswith(b";\n"))
        check("catalog.js assigns the expected global",
              GLOBAL_NAME.encode("utf-8") in committed)

    # --- the HSK entry describes the real runtime files -------------------
    hsk = [p for p in catalog["packs"] if p["packId"] == "hsk"]
    check("catalog declares exactly one pack", len(catalog["packs"]) == 1)
    check("catalog contains hsk", len(hsk) == 1)
    if hsk:
        e = hsk[0]
        check("cardsPath is the legacy data.js", e["cardsPath"] == "data.js")
        check("manifestPath is the legacy adapter",
              e["manifestPath"] == "packs/hsk/hsk-content-pack.js")
        check("declared idRange is 1..999999",
              e["idRange"] == {"min": 1, "max": 999999})
        check("allocated is 5002 cards spanning 1..5002",
              e["allocated"] == {"count": 5002, "min": 1, "max": 5002})
        check("contentChecksum is data.js bytes",
              e["contentChecksum"] ==
              "sha256:" + sha256_file(os.path.join(APP_ROOT, "data.js")))
        check("install kind is legacy-installed",
              e["install"]["kind"] == "legacy-installed")
        check("sourceChecksum basis is documented as raw workbook bytes",
              e["install"]["sourceChecksumBasis"] == "raw-workbook-bytes")
        check("sourceChecksum is NOT claimed to be a CSI",
              "csi" not in e["install"]["sourceChecksumBasis"].lower())
        check("pack is launch-visible", e["launch"]["visible"] is True)
        check("audio locale comes from the manifest",
              e["audio"]["locale"] == "zh-CN")
        check("allocated sits inside the declared range",
              e["idRange"]["min"] <= e["allocated"]["min"] and
              e["allocated"]["max"] <= e["idRange"]["max"])

    # --- the cards payload still honors the frozen HSK contract -----------
    rows = all_rows.get("hsk", [])
    ids = [r["id"] for r in rows]
    check("5002 cards", len(rows) == 5002)
    check("ids are contiguous 1..5002", ids == list(range(1, 5003)))
    check("ids are unique", len(set(ids)) == len(ids))
    check("eight-field card shape",
          all(set(r.keys()) == {"id", "level", "word", "pinyin", "meaning",
                                "example", "examplePinyin", "translation"}
              for r in rows))

    # --- generation is independent of working-tree line endings -----------
    # A CRLF checkout must produce the SAME catalog as an LF checkout, or the
    # embedded runtime-asset checksums disagree with what a clone deploys.
    import tempfile
    manifest_rel = LEGACY_SOURCES[0]["manifestPath"]
    manifest_abs = os.path.join(APP_ROOT, manifest_rel)
    lf = canonical_bytes(manifest_abs)
    # Both forms are written explicitly, because the checked-out copy of
    # manifest_abs may itself be CRLF or LF depending on the platform.
    with tempfile.TemporaryDirectory() as tmp:
        crlf_path = os.path.join(tmp, "crlf.js")
        lf_path = os.path.join(tmp, "lf.js")
        with open(crlf_path, "wb") as fh:
            fh.write(lf.replace(b"\n", b"\r\n"))
        with open(lf_path, "wb") as fh:
            fh.write(lf)
        check("checksum ignores CRLF vs LF",
              sha256_file(crlf_path) == sha256_file(lf_path))
        check("byte count ignores CRLF vs LF",
              file_bytes(crlf_path) == file_bytes(lf_path))
        check("the catalog records the LF byte count",
              file_bytes(lf_path) == len(lf))
        # ...but binary hashing must NOT normalize, or workbook hashes break.
        check("binary hashing does not normalize",
              sha256_file(crlf_path, binary=True) !=
              sha256_file(lf_path, binary=True))

    # --- path validation is generic and fails closed ----------------------
    for bad, label in [
        ("/etc/passwd", "absolute"),
        ("../../secret.js", "traversal"),
        ("https://cdn.example/x.js", "url"),
        ("packs\\hsk\\x.js", "backslash"),
        ("C:/x.js", "drive"),
        ("packs//x.js", "empty segment"),
    ]:
        try:
            check_rel_path(bad, "test")
            check("rejects %s path" % label, False)
        except ValueError:
            check("rejects %s path" % label, True)

    # containment is enforced against the real app root
    try:
        resolve_contained("data.js", APP_ROOT, "ok")
        check("accepts a contained runtime asset", True)
    except ValueError:
        check("accepts a contained runtime asset", False)

    print(json.dumps({"suite": "pack_catalog_legacy",
                      "pass": not fails, "failures": fails}))
    return 0 if not fails else 1


if __name__ == "__main__":
    sys.exit(main())
